name: Dev CI

on:
  workflow_dispatch:
    inputs:
      generate_artifacts:
        description: 'Generate and upload build artifacts'
        required: true
        default: false
        type: boolean
  pull_request:

permissions: { }

# Cancel previous workflows if they are the same workflow on same ref (branch/tags)
# with the same event (push/pull_request) even they are in progress.
# This setting will help reduce the number of duplicated workflows.
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.event_name }}
  cancel-in-progress: true

jobs:
  dev_ubuntu:
    name: Build Sirius on Ubuntu
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Set Sirius output variables
        id: sirius-variables
        shell: bash
        continue-on-error: false
        run: |
          echo "SIRIUS_INSTALL_DIR=ubuntu_sirius-solver-install" >> "$GITHUB_ENV"
          echo "SIRIUS_INSTALL_PATH=${{ github.workspace }}/$SIRIUS_INSTALL_DIR" >> "$GITHUB_ENV"
          echo "ARCHIVE_NAME=ubuntu_sirius-solver.zip" >> "$GITHUB_ENV"
          echo "ARCHIVE_PATH=${{ github.workspace }}/$ARCHIVE_NAME" >> "$GITHUB_ENV"

      - name: Configure Sirius
        shell: bash
        run: |
          cmake -S src \
                -B build \
                -DCMAKE_BUILD_TYPE=Release \
                -DCMAKE_INSTALL_PREFIX="${SIRIUS_INSTALL_DIR}"

      - name: Build Sirius
        shell: bash
        run: |
          cmake --build build --config Release -j14

      - name: Install Sirius
        shell: bash
        run: |
          cmake --install build

      - name: Extract Sirius version
        shell: bash
        run: |
          CONFIG_FILE="build/CPackConfig.cmake"
          if [ ! -f "$CONFIG_FILE" ]; then
          echo "Error: CPackConfig.cmake not found. Make sure CMake configuration and build were successful."
          exit 1
          fi
          MAJOR=$(grep 'set(CPACK_PACKAGE_VERSION_MAJOR' "$CONFIG_FILE" | sed -E 's/.*"([0-9]+)".*/\1/')
          MINOR=$(grep 'set(CPACK_PACKAGE_VERSION_MINOR' "$CONFIG_FILE" | sed -E 's/.*"([0-9]+)".*/\1/')
          PATCH=$(grep 'set(CPACK_PACKAGE_VERSION_PATCH' "$CONFIG_FILE" | sed -E 's/.*"([0-9]+)".*/\1/')
          VERSION="$MAJOR.$MINOR.$PATCH"
          echo "SIRIUS_VERSION=$VERSION" >> "$GITHUB_ENV"

      - name: Upload Sirius archive
#        if: ${{ github.event_name == 'workflow_dispatch' && inputs.generate_artifacts }}
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # 4.6.2
        with:
          name: sirius-solver-install-ubuntu-${{ env.SIRIUS_VERSION }}
          path: ${{ env.SIRIUS_INSTALL_DIR }}