name: Dev CI

on:
  workflow_dispatch:
    inputs:
      generate_artifacts:
        description: 'Generate and upload build artifacts'
        required: true
        default: false
        type: boolean
  pull_request:

permissions: { }

# Cancel previous workflows if they are the same workflow on same ref (branch/tags)
# with the same event (push/pull_request) even they are in progress.
# This setting will help reduce the number of duplicated workflows.
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.event_name }}
  cancel-in-progress: true

jobs:
  dev_ubuntu:
    name: Build Sirius on Ubuntu
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Set Sirius output variables
        id: sirius-variables
        shell: bash
        continue-on-error: false
        run: >
          echo "SIRIUS_INSTALL_DIR=ubuntu_sirius-solver-install" >> "$GITHUB_ENV"

      - name: Configure Sirius
        shell: bash
        run: |
          cmake -S src -B build -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX="${{ env.SIRIUS_INSTALL_DIR }}"

      - name: Build Sirius
        shell: bash
        run: |
          cmake --build build --config Release --parallel

      - name: Install Sirius
        shell: bash
        run: |
          cmake --install build

      - name: Extract Sirius version
        shell: bash
        run: |
          SIRIUS_VERSION=$(grep -m1 'SIRIUS_SOLVER_VERSION ' ${{ env.SIRIUS_INSTALL_DIR }}/include/version.h | cut -d '"' -f2)
          echo "SIRIUS_VERSION=$SIRIUS_VERSION" >> "$GITHUB_ENV"

      - name: Prepare archive directory
        shell: bash
        run: |
          mkdir -p sirius-artifact
          mv "${{ env.SIRIUS_INSTALL_DIR }}" sirius-artifact/

      - name: Upload Sirius archive
        if: ${{ github.event_name == 'workflow_dispatch' && inputs.generate_artifacts }}
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # 4.6.2
        with:
          name: sirius-solver-install-ubuntu-${{ env.SIRIUS_VERSION }}
          path: sirius-artifact

  dev_centos7:
    name: Build Sirius on CentOS7
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Build the Docker image
        run: >
          docker build -t centos7withcmake:latest $GITHUB_WORKSPACE --file $GITHUB_WORKSPACE/.github/workflows/docker/Dockerfile

      - name: Run build steps in Docker container
        run: |
          docker run --name build_container -v $GITHUB_WORKSPACE:/workspace centos7withcmake:latest /bin/bash -c "
            cd /workspace &&
            cmake -S src -B build -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=centos7_sirius-solver-install &&
            cmake --build build --config Release -j14 &&
            cmake --install build &&
            mkdir -p sirius-artifact &&
            mv centos7_sirius-solver-install sirius-artifact/
          "

      - name: Extract Sirius version
        run: |
          SIRIUS_VERSION=$(grep -m1 'SIRIUS_SOLVER_VERSION ' centos7_sirius-solver-install/include/version.h | cut -d '"' -f2)
          echo "SIRIUS_VERSION=$SIRIUS_VERSION" >> "$GITHUB_ENV"

      - name: Upload Sirius archive
        if: github.event_name == 'workflow_dispatch' && inputs.generate_artifacts == 'true'
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # 4.6.2
        with:
          name: sirius-solver-install-centos7-${{ env.SIRIUS_VERSION }}
          path: sirius-artifact

  dev_oracle_linux8:
    name: Build Sirius on Oracle Linux 8
    runs-on: ubuntu-latest
    container: 'oraclelinux:8'
    steps:
      - name: Install required dependencies
        run: |
          dnf update -y
          dnf install -y epel-release dnf-plugins-core
          dnf config-manager --set-enabled ol8_codeready_builder
          dnf install -y git cmake make gcc gcc-c++ ninja-build || true
          dnf clean all

      - name: Checkout sources
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Set Sirius output variables
        id: sirius-variables
        shell: bash
        run: >
          echo "SIRIUS_INSTALL_DIR=ol8_sirius-solver-install" >> "$GITHUB_ENV"

      - name: Configure Sirius
        shell: bash
        run: |
          cmake -S src \
                -B build \
                -DCMAKE_BUILD_TYPE=Release \
                -DCMAKE_INSTALL_PREFIX="${{ env.SIRIUS_INSTALL_DIR }}"

      - name: Build Sirius
        shell: bash
        run: >
          cmake --build build --config Release --parallel

      - name: Install Sirius
        shell: bash
        run: >
          cmake --install build

      - name: Extract Sirius version
        shell: bash
        run: |
          SIRIUS_VERSION=$(grep -m1 'SIRIUS_SOLVER_VERSION ' ${{ env.SIRIUS_INSTALL_DIR }}/include/version.h | cut -d '"' -f2)
          echo "SIRIUS_VERSION=$SIRIUS_VERSION" >> "$GITHUB_ENV"

      - name: Prepare archive directory
        shell: bash
        run: |
          mkdir -p sirius-artifact
          mv "${{ env.SIRIUS_INSTALL_DIR }}" sirius-artifact/

      - name: Upload Sirius archive
        if: ${{ github.event_name == 'workflow_dispatch' && inputs.generate_artifacts }}
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # 4.6.2
        with:
          name: sirius-solver-install-ol8-${{ env.SIRIUS_VERSION }}
          path: sirius-artifact

  dev_windows:
    name: Build Sirius on Windows
    runs-on: windows-latest
    defaults:
      run:
        shell: pwsh
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Set Sirius output variables
        id: sirius-variables
        continue-on-error: false
        run: >
          echo "SIRIUS_INSTALL_DIR=windows_sirius-solver-install" | Out-File -FilePath $env:GITHUB_ENV -Append

      - name: Configure Sirius
        run: >
          cmake -S src -B build -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX="${{ env.SIRIUS_INSTALL_DIR }}"

      - name: Build Sirius
        run: >
          cmake --build build --config Release --parallel

      - name: Install Sirius
        run: >
          cmake --install build

      - name: Extract Sirius version
        run: |
          $versionLine = Get-Content "${{ env.SIRIUS_INSTALL_DIR }}\include\version.h" | Select-String -Pattern '#define SIRIUS_SOLVER_VERSION '
          $SIRIUS_VERSION = $versionLine -replace '.*"([^"]+)".*', '$1'
          echo "SIRIUS_VERSION=$SIRIUS_VERSION" | Out-File -FilePath $env:GITHUB_ENV -Append

      - name: Prepare archive directory
        run: |
          New-Item -ItemType Directory -Path sirius-artifact | Out-Null
          Move-Item -Path "${{ env.SIRIUS_INSTALL_DIR }}" -Destination "sirius-artifact\" -Force

      - name: Upload Sirius archive
        if: ${{ github.event_name == 'workflow_dispatch' && inputs.generate_artifacts }}
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # 4.6.2
        with:
          name: sirius-solver-install-windows-${{ env.SIRIUS_VERSION }}
          path: sirius-artifact